# Generated by Django 5.0.1 on 2024-09-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип голоса')),
            ],
            options={
                'verbose_name': 'Тип голоса',
                'verbose_name_plural': 'Типы голоса',
                'db_table': 'voice_type',
            },
        ),
    ]
