# Generated by Django 5.0.1 on 2024-09-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('sec_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('voice', models.ForeignKey(db_column='voice_id', on_delete=django.db.models.deletion.CASCADE, to='core.voice')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'person',
            },
        ),
    ]
