# Generated by Django 5.0.1 on 2024-09-19 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_register',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
